name: Deploy

on:
  release:
    types: [created]

jobs:
  docker_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
              docker build . --file Dockerfile --tag ghcr.io/technokrat/fahrplan/fahrplan:${{  github.ref_name }} --tag ghcr.io/technokrat/fahrplan/fahrplan:latest
              docker push ghcr.io/technokrat/fahrplan/fahrplan:${{  github.ref_name }}
              docker push ghcr.io/technokrat/fahrplan/fahrplan:latest
